CREATE DATABASE ticketing;
GO

USE ticketing;
GO

CREATE TABLE INCIDENT_TICKETS (
    TICKET_NUMBER VARCHAR(50) PRIMARY KEY,
    STATUS VARCHAR(50),
    PRIORITY VARCHAR(50),
    COMPANY VARCHAR(100),
    PROJECT VARCHAR(100),
    TEAM VARCHAR(50),
    ASSIGNED_PERSON VARCHAR(100),
    SERVICE VARCHAR(100),
    DESCRIPTION TEXT,
    NOTES TEXT,
    RESOLUTION TEXT,
    CATEGORY_TIER_1 VARCHAR(100),
    CATEGORY_TIER_2 VARCHAR(100),
    CATEGORY_TIER_3 VARCHAR(100),
    SUBMIT_DATETIME DATETIME,
    RESOLVED_DATETIME DATETIME,
    CLOSED_DATETIME DATETIME,
    LAST_MODIFIED_DATETIME DATETIME,
    ESTIMATED_RESOLUTION_DATETIME DATETIME,
    RESOLUTION_CATEGORY VARCHAR(100),
    PENDING_DURATION INTEGER
);
GO